export { default as Home } from "./Home/Home"
export { default as Login  } from "./auth/Login"
export { default as Register  } from "./auth/Register"
export { default as Error404  } from "./Error/Error404"
export { default as Callback } from "./Callback/Callback"
export { default as AboutUs} from "./AboutUs/AboutUsPage"
export { default as Events } from "./Events/Events"
export {default as EventPage} from "./Event Page/EventPage"
export { default as Cart } from "./Cart/Cart"
